/** generated by ParGen **/
#include "PxmlToken.hpp"

std::ostream& operator<< (std::ostream& os, ParsePxml::Position& pos){
    return os << pos.path.string() << ":" << pos.line << ":" << pos.column;
}

