/** generated by ParGen **/
#ifndef ParGen_TokenType_PPToken_guard
#define ParGen_TokenType_PPToken_guard

#include <string>
#include <cstddef>
#include <unordered_set>
        
#include <iostream>
#include <filesystem>
#include <variant>

namespace WasmVM::PP {

struct Position {
    std::filesystem::path path;
    size_t line;
    size_t column;
};

namespace TokenType {

struct HeaderName : public std::string {};

struct Identifier : public std::string {};

struct Number : public std::string {
    template<typename T>
    T get();
};

struct Character : public std::variant<int, wchar_t, char16_t, char32_t> {};

struct String : public std::variant<std::string, std::u8string, std::wstring, std::u16string> {};

struct NewLine {};

} // namespace TokenType

struct PPToken : public std::variant<
  TokenType::HeaderName,
  TokenType::Identifier,
  TokenType::Number,
  TokenType::Character,
  TokenType::String,
  TokenType::NewLine
> {

    std::unordered_set<std::string> expanded;
    bool skipped = false;
    Position pos;
};

} // namespace WasmVM::PP

std::ostream& operator<< (std::ostream&, WasmVM::PP::Position&);

#endif 
