/** generated by ParGen **/
#include "PPToken.hpp"

// TODO: template<> T TokenType::Number::get<typename T>()

std::ostream& operator<< (std::ostream& os, WasmVM::PP::Position& pos){
    return os << pos.path.string() << ":" << pos.line << ":" << pos.column;
}

