/** generated by ParGen **/
#ifndef ParGen_Pargen__Tokens_Token_guard
#define ParGen_Pargen__Tokens_Token_guard

#include <string>
        
#include <iostream>
#include <filesystem>
#include <variant>

namespace PXML {

struct Position {
    std::filesystem::path path;
    size_t line;
    size_t column;
};

namespace Pargen::Tokens {

struct Doctype {};

struct Equal {};

struct Close {};

struct Inline {};

struct Bool {
    bool value;
};

struct Number {
    double value;
};

struct Tag {
    std::string value;
};

struct Tail {
    std::string value;
};

struct String {
    std::string value;
};

struct Text {
    std::string value;
};

struct ID {
    std::string value;
};

struct Entity {
    std::string value;
};

struct Space {
    std::string value;
};

} // namespace Pargen::Tokens

struct Token : public std::variant<
  Pargen::Tokens::Doctype,
  Pargen::Tokens::Equal,
  Pargen::Tokens::Close,
  Pargen::Tokens::Inline,
  Pargen::Tokens::Bool,
  Pargen::Tokens::Number,
  Pargen::Tokens::Tag,
  Pargen::Tokens::Tail,
  Pargen::Tokens::String,
  Pargen::Tokens::Text,
  Pargen::Tokens::ID,
  Pargen::Tokens::Entity,
  Pargen::Tokens::Space
> {
    Position pos;
};

} // namespace PXML

std::ostream& operator<< (std::ostream&, PXML::Position&);

#endif 
